site_name: PythonOCC Tutorial

theme:
  name: readthedocs
#  name: material
#  highlightjs: true


nav:
  - Introduction:
    - Modeling Data: modeling_data.md
  - Tutorial:
    - HelloBox: hellobox.md
    - Geometry:
      - Introduction: geom_intro.md
    #- Conceptos: conceptos.md
    #- Propiedades:
    #  - Introducci칩n: propiedades.md
    #  - Presi칩n: presion.md
    #- Estado: estado.md
    #- Proceso: proceso.md
    #- Fase: fase.md
    #- Equilibrio: equilibrio.md

  #- Primera Ley de la Termodin치mica:
  #  - Introducci칩n: 1st_intro.md
  #  - Aplicaciones:
  #      - Ciclos:
  #          - Carnot: 1st_ciclo_carnot.md



extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
- admonition
- codehilite
- pymdownx.details
- pymdownx.superfences
- pymdownx.arithmatex
- mdx_math:
    enable_dollar_delimiter: true

plugins:
- search
